### ISSUE TITLE
Unavailable fare classes reported as price drops

### ISSUE THREAD

**Issue by infinite-monkeys** [xur17/southwest-alerts#5]
I have a points reservation for a WGA fare. It's about 2 months out, but there are no more WGA fares available. The Anytime fare is an increase over what I have booked, but the app alerts a "Price drop of 10868 points"

**Comment by soccerjoshj07** [comment]
Adding this IF/else check in app.py works:

###             **if refund_amount == itinerary_price:
                logging.info('Fare class is sold out..')
            else:**
                if refund_amount > 0:
                    logging.info('Sending email for price drop')

**Comment by infinite-monkeys** [comment]
Thanks for the tip. I implemented a patch for this in a slightly different way.
